# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/extensions/udp_packet_writer/v3/udp_gso_batch_writer_factory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from udpa.annotations import status_pb2 as udpa_dot_annotations_dot_status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHenvoy/extensions/udp_packet_writer/v3/udp_gso_batch_writer_factory.proto\x12%envoy.extensions.udp_packet_writer.v3\x1a\x1dudpa/annotations/status.proto\"\x1a\n\x18UdpGsoBatchWriterFactoryB\xc0\x01\n3io.envoyproxy.envoy.extensions.udp_packet_writer.v3B\x1dUdpGsoBatchWriterFactoryProtoP\x01Z`github.com/envoyproxy/go-control-plane/envoy/extensions/udp_packet_writer/v3;udp_packet_writerv3\xba\x80\xc8\xd1\x06\x02\x10\x02\x62\x06proto3')



_UDPGSOBATCHWRITERFACTORY = DESCRIPTOR.message_types_by_name['UdpGsoBatchWriterFactory']
UdpGsoBatchWriterFactory = _reflection.GeneratedProtocolMessageType('UdpGsoBatchWriterFactory', (_message.Message,), {
  'DESCRIPTOR' : _UDPGSOBATCHWRITERFACTORY,
  '__module__' : 'envoy.extensions.udp_packet_writer.v3.udp_gso_batch_writer_factory_pb2'
  # @@protoc_insertion_point(class_scope:envoy.extensions.udp_packet_writer.v3.UdpGsoBatchWriterFactory)
  })
_sym_db.RegisterMessage(UdpGsoBatchWriterFactory)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n3io.envoyproxy.envoy.extensions.udp_packet_writer.v3B\035UdpGsoBatchWriterFactoryProtoP\001Z`github.com/envoyproxy/go-control-plane/envoy/extensions/udp_packet_writer/v3;udp_packet_writerv3\272\200\310\321\006\002\020\002'
  _UDPGSOBATCHWRITERFACTORY._serialized_start=146
  _UDPGSOBATCHWRITERFACTORY._serialized_end=172
# @@protoc_insertion_point(module_scope)
