# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xds/type/v3/range.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17xds/type/v3/range.proto\x12\x0bxds.type.v3\"(\n\nInt64Range\x12\r\n\x05start\x18\x01 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x03\"(\n\nInt32Range\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\")\n\x0b\x44oubleRange\x12\r\n\x05start\x18\x01 \x01(\x01\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x01\x42J\n\x16\x63om.github.xds.type.v3B\nRangeProtoP\x01Z\"github.com/cncf/xds/go/xds/type/v3b\x06proto3')



_INT64RANGE = DESCRIPTOR.message_types_by_name['Int64Range']
_INT32RANGE = DESCRIPTOR.message_types_by_name['Int32Range']
_DOUBLERANGE = DESCRIPTOR.message_types_by_name['DoubleRange']
Int64Range = _reflection.GeneratedProtocolMessageType('Int64Range', (_message.Message,), {
  'DESCRIPTOR' : _INT64RANGE,
  '__module__' : 'xds.type.v3.range_pb2'
  # @@protoc_insertion_point(class_scope:xds.type.v3.Int64Range)
  })
_sym_db.RegisterMessage(Int64Range)

Int32Range = _reflection.GeneratedProtocolMessageType('Int32Range', (_message.Message,), {
  'DESCRIPTOR' : _INT32RANGE,
  '__module__' : 'xds.type.v3.range_pb2'
  # @@protoc_insertion_point(class_scope:xds.type.v3.Int32Range)
  })
_sym_db.RegisterMessage(Int32Range)

DoubleRange = _reflection.GeneratedProtocolMessageType('DoubleRange', (_message.Message,), {
  'DESCRIPTOR' : _DOUBLERANGE,
  '__module__' : 'xds.type.v3.range_pb2'
  # @@protoc_insertion_point(class_scope:xds.type.v3.DoubleRange)
  })
_sym_db.RegisterMessage(DoubleRange)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.github.xds.type.v3B\nRangeProtoP\001Z\"github.com/cncf/xds/go/xds/type/v3'
  _INT64RANGE._serialized_start=40
  _INT64RANGE._serialized_end=80
  _INT32RANGE._serialized_start=82
  _INT32RANGE._serialized_end=122
  _DOUBLERANGE._serialized_start=124
  _DOUBLERANGE._serialized_end=165
# @@protoc_insertion_point(module_scope)
