# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/extensions/load_balancing_policies/maglev/v3/maglev.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from udpa.annotations import status_pb2 as udpa_dot_annotations_dot_status__pb2
from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?envoy/extensions/load_balancing_policies/maglev/v3/maglev.proto\x12\x32\x65nvoy.extensions.load_balancing_policies.maglev.v3\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1dudpa/annotations/status.proto\x1a\x17validate/validate.proto\"F\n\x06Maglev\x12<\n\ntable_size\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.UInt64ValueB\n\xfa\x42\x07\x32\x05\x18\xcb\x96\xb1\x02\x42\xbd\x01\n@io.envoyproxy.envoy.extensions.load_balancing_policies.maglev.v3B\x0bMaglevProtoP\x01Zbgithub.com/envoyproxy/go-control-plane/envoy/extensions/load_balancing_policies/maglev/v3;maglevv3\xba\x80\xc8\xd1\x06\x02\x10\x02\x62\x06proto3')



_MAGLEV = DESCRIPTOR.message_types_by_name['Maglev']
Maglev = _reflection.GeneratedProtocolMessageType('Maglev', (_message.Message,), {
  'DESCRIPTOR' : _MAGLEV,
  '__module__' : 'envoy.extensions.load_balancing_policies.maglev.v3.maglev_pb2'
  # @@protoc_insertion_point(class_scope:envoy.extensions.load_balancing_policies.maglev.v3.Maglev)
  })
_sym_db.RegisterMessage(Maglev)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n@io.envoyproxy.envoy.extensions.load_balancing_policies.maglev.v3B\013MaglevProtoP\001Zbgithub.com/envoyproxy/go-control-plane/envoy/extensions/load_balancing_policies/maglev/v3;maglevv3\272\200\310\321\006\002\020\002'
  _MAGLEV.fields_by_name['table_size']._options = None
  _MAGLEV.fields_by_name['table_size']._serialized_options = b'\372B\0072\005\030\313\226\261\002'
  _MAGLEV._serialized_start=207
  _MAGLEV._serialized_end=277
# @@protoc_insertion_point(module_scope)
