# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/harness/cases/sort/sort.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#tests/harness/cases/sort/sort.proto\x12\x18tests.harness.cases.sort*5\n\tDirection\x12\x15\n\x11UNKNOWN_DIRECTION\x10\x00\x12\x07\n\x03\x41SC\x10\x01\x12\x08\n\x04\x44\x45SC\x10\x02\x42LZJgithub.com/envoyproxy/protoc-gen-validate/tests/harness/cases/sort/go;sortb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tests.harness.cases.sort.sort_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZJgithub.com/envoyproxy/protoc-gen-validate/tests/harness/cases/sort/go;sort'
  _globals['_DIRECTION']._serialized_start=65
  _globals['_DIRECTION']._serialized_end=118
# @@protoc_insertion_point(module_scope)
