"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class OrcaLoadReportRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    REPORT_INTERVAL_FIELD_NUMBER: builtins.int
    REQUEST_COST_NAMES_FIELD_NUMBER: builtins.int
    @property
    def report_interval(self) -> google.protobuf.duration_pb2.Duration:
        """Interval for generating Open RCA core metric responses."""
        pass
    @property
    def request_cost_names(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]:
        """Request costs to collect. If this is empty, all known requests costs tracked by
        the load reporting agent will be returned. This provides an opportunity for
        the client to selectively obtain a subset of tracked costs.
        """
        pass
    def __init__(self,
        *,
        report_interval : typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        request_cost_names : typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"report_interval",b"report_interval"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"report_interval",b"report_interval",u"request_cost_names",b"request_cost_names"]) -> None: ...
global___OrcaLoadReportRequest = OrcaLoadReportRequest
