# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/extensions/filters/http/aws_request_signing/v3/aws_request_signing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from envoy.type.matcher.v3 import string_pb2 as envoy_dot_type_dot_matcher_dot_v3_dot_string__pb2
from udpa.annotations import status_pb2 as udpa_dot_annotations_dot_status__pb2
from udpa.annotations import versioning_pb2 as udpa_dot_annotations_dot_versioning__pb2
from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nNenvoy/extensions/filters/http/aws_request_signing/v3/aws_request_signing.proto\x12\x34\x65nvoy.extensions.filters.http.aws_request_signing.v3\x1a\"envoy/type/matcher/v3/string.proto\x1a\x1dudpa/annotations/status.proto\x1a!udpa/annotations/versioning.proto\x1a\x17validate/validate.proto\"\x94\x02\n\x11\x41wsRequestSigning\x12\x1d\n\x0cservice_name\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01\x12\x17\n\x06region\x18\x02 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01\x12\x14\n\x0chost_rewrite\x18\x03 \x01(\t\x12\x1c\n\x14use_unsigned_payload\x18\x04 \x01(\x08\x12\x44\n\x16match_excluded_headers\x18\x05 \x03(\x0b\x32$.envoy.type.matcher.v3.StringMatcher:M\x9a\xc5\x88\x1eH\nFenvoy.config.filter.http.aws_request_signing.v2alpha.AwsRequestSigningB\xd9\x01\nBio.envoyproxy.envoy.extensions.filters.http.aws_request_signing.v3B\x16\x41wsRequestSigningProtoP\x01Zqgithub.com/envoyproxy/go-control-plane/envoy/extensions/filters/http/aws_request_signing/v3;aws_request_signingv3\xba\x80\xc8\xd1\x06\x02\x10\x02\x62\x06proto3')



_AWSREQUESTSIGNING = DESCRIPTOR.message_types_by_name['AwsRequestSigning']
AwsRequestSigning = _reflection.GeneratedProtocolMessageType('AwsRequestSigning', (_message.Message,), {
  'DESCRIPTOR' : _AWSREQUESTSIGNING,
  '__module__' : 'envoy.extensions.filters.http.aws_request_signing.v3.aws_request_signing_pb2'
  # @@protoc_insertion_point(class_scope:envoy.extensions.filters.http.aws_request_signing.v3.AwsRequestSigning)
  })
_sym_db.RegisterMessage(AwsRequestSigning)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\nBio.envoyproxy.envoy.extensions.filters.http.aws_request_signing.v3B\026AwsRequestSigningProtoP\001Zqgithub.com/envoyproxy/go-control-plane/envoy/extensions/filters/http/aws_request_signing/v3;aws_request_signingv3\272\200\310\321\006\002\020\002'
  _AWSREQUESTSIGNING.fields_by_name['service_name']._options = None
  _AWSREQUESTSIGNING.fields_by_name['service_name']._serialized_options = b'\372B\004r\002\020\001'
  _AWSREQUESTSIGNING.fields_by_name['region']._options = None
  _AWSREQUESTSIGNING.fields_by_name['region']._serialized_options = b'\372B\004r\002\020\001'
  _AWSREQUESTSIGNING._options = None
  _AWSREQUESTSIGNING._serialized_options = b'\232\305\210\036H\nFenvoy.config.filter.http.aws_request_signing.v2alpha.AwsRequestSigning'
  _AWSREQUESTSIGNING._serialized_start=264
  _AWSREQUESTSIGNING._serialized_end=540
# @@protoc_insertion_point(module_scope)
