# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tests/harness/cases/other_package/embed.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tests/harness/cases/other_package/embed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-tests/harness/cases/other_package/embed.proto\x12!tests.harness.cases.other_package\x1a\x17validate/validate.proto\"\x8d\x01\n\x05\x45mbed\x12\x14\n\x03val\x18\x01 \x01(\x03\x42\x07\xfa\x42\x04\"\x02 \x00\x1a,\n\x0b\x44oubleEmbed\"\x1d\n\x10\x44oubleEnumerated\x12\t\n\x05VALUE\x10\x00\"\x17\n\nEnumerated\x12\t\n\x05VALUE\x10\x00\"\'\n\tFooNumber\x12\x08\n\x04ZERO\x10\x00\x12\x07\n\x03ONE\x10\x01\x12\x07\n\x03TWO\x10\x02\x42^Z\\github.com/envoyproxy/protoc-gen-validate/tests/harness/cases/other_package/go;other_packageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tests.harness.cases.other_package.embed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\\github.com/envoyproxy/protoc-gen-validate/tests/harness/cases/other_package/go;other_package'
  _globals['_EMBED'].fields_by_name['val']._loaded_options = None
  _globals['_EMBED'].fields_by_name['val']._serialized_options = b'\372B\004\"\002 \000'
  _globals['_EMBED']._serialized_start=110
  _globals['_EMBED']._serialized_end=251
  _globals['_EMBED_DOUBLEEMBED']._serialized_start=141
  _globals['_EMBED_DOUBLEEMBED']._serialized_end=185
  _globals['_EMBED_DOUBLEEMBED_DOUBLEENUMERATED']._serialized_start=156
  _globals['_EMBED_DOUBLEEMBED_DOUBLEENUMERATED']._serialized_end=185
  _globals['_EMBED_ENUMERATED']._serialized_start=187
  _globals['_EMBED_ENUMERATED']._serialized_end=210
  _globals['_EMBED_FOONUMBER']._serialized_start=212
  _globals['_EMBED_FOONUMBER']._serialized_end=251
# @@protoc_insertion_point(module_scope)
