"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class ProxyProtocolConfig(google.protobuf.message.Message):
    """[#protodoc-title: Proxy Protocol]

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class Version(_Version, metaclass=_VersionEnumTypeWrapper):
        pass
    class _Version:
        V = typing.NewType('V', builtins.int)
    class _VersionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Version.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        V1 = ProxyProtocolConfig.Version.V(0)
        """PROXY protocol version 1. Human readable format."""

        V2 = ProxyProtocolConfig.Version.V(1)
        """PROXY protocol version 2. Binary format."""


    V1 = ProxyProtocolConfig.Version.V(0)
    """PROXY protocol version 1. Human readable format."""

    V2 = ProxyProtocolConfig.Version.V(1)
    """PROXY protocol version 2. Binary format."""


    VERSION_FIELD_NUMBER: builtins.int
    version: global___ProxyProtocolConfig.Version.V = ...
    """The PROXY protocol version to use. See https://www.haproxy.org/download/2.1/doc/proxy-protocol.txt for details"""

    def __init__(self,
        *,
        version : global___ProxyProtocolConfig.Version.V = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"version",b"version"]) -> None: ...
global___ProxyProtocolConfig = ProxyProtocolConfig
