"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import audit.audit_pb2
import builtins
import collections.abc
import crypt.crypt_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class DecryptAuditRecordsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEALED_AUDIT_RECORDS_FIELD_NUMBER: builtins.int
    @property
    def sealed_audit_records(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[crypt.crypt_pb2.SealedMessage]: ...
    def __init__(
        self,
        *,
        sealed_audit_records: collections.abc.Iterable[crypt.crypt_pb2.SealedMessage] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["sealed_audit_records", b"sealed_audit_records"]) -> None: ...

global___DecryptAuditRecordsRequest = DecryptAuditRecordsRequest

class DecryptAuditRecordsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUDIT_RECORDS_FIELD_NUMBER: builtins.int
    @property
    def audit_records(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[audit.audit_pb2.Record]: ...
    def __init__(
        self,
        *,
        audit_records: collections.abc.Iterable[audit.audit_pb2.Record] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["audit_records", b"audit_records"]) -> None: ...

global___DecryptAuditRecordsResponse = DecryptAuditRecordsResponse
