"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import key_chain_pb2
import namespaces_pb2
import policy_pb2
import routes_pb2
import settings_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ConsoleConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_PAIRS_FIELD_NUMBER: builtins.int
    NAMESPACES_FIELD_NUMBER: builtins.int
    POLICIES_FIELD_NUMBER: builtins.int
    ROUTES_FIELD_NUMBER: builtins.int
    SETTINGS_FIELD_NUMBER: builtins.int
    @property
    def key_pairs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[key_chain_pb2.KeyPair]: ...
    @property
    def namespaces(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[namespaces_pb2.Namespace]: ...
    @property
    def policies(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[policy_pb2.Policy]: ...
    @property
    def routes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[routes_pb2.Route]: ...
    @property
    def settings(self) -> settings_pb2.Settings: ...
    def __init__(
        self,
        *,
        key_pairs: collections.abc.Iterable[key_chain_pb2.KeyPair] | None = ...,
        namespaces: collections.abc.Iterable[namespaces_pb2.Namespace] | None = ...,
        policies: collections.abc.Iterable[policy_pb2.Policy] | None = ...,
        routes: collections.abc.Iterable[routes_pb2.Route] | None = ...,
        settings: settings_pb2.Settings | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["settings", b"settings"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["key_pairs", b"key_pairs", "namespaces", b"namespaces", "policies", b"policies", "routes", b"routes", "settings", b"settings"]) -> None: ...

global___ConsoleConfig = ConsoleConfig
