"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import databroker_svc_pb2
import google.protobuf.empty_pb2
import grpc

class DataBrokerStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    ListDataBrokerRecords: grpc.UnaryUnaryMultiCallable[
        databroker_svc_pb2.ListDataBrokerRecordsRequest,
        databroker_svc_pb2.ListDataBrokerRecordsResponse,
    ]
    ListDataBrokerRecordTypes: grpc.UnaryUnaryMultiCallable[
        google.protobuf.empty_pb2.Empty,
        databroker_svc_pb2.ListDataBrokerRecordTypesResponse,
    ]

class DataBrokerServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def ListDataBrokerRecords(
        self,
        request: databroker_svc_pb2.ListDataBrokerRecordsRequest,
        context: grpc.ServicerContext,
    ) -> databroker_svc_pb2.ListDataBrokerRecordsResponse: ...
    @abc.abstractmethod
    def ListDataBrokerRecordTypes(
        self,
        request: google.protobuf.empty_pb2.Empty,
        context: grpc.ServicerContext,
    ) -> databroker_svc_pb2.ListDataBrokerRecordTypesResponse: ...

def add_DataBrokerServicer_to_server(servicer: DataBrokerServicer, server: grpc.Server) -> None: ...
