# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pomerium.pb.external_data_sources_pb2 as external__data__sources__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ExternalDataSourceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeleteExternalDataSource = channel.unary_unary(
                '/pomerium.dashboard.ExternalDataSourceService/DeleteExternalDataSource',
                request_serializer=external__data__sources__pb2.DeleteExternalDataSourceRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetExternalDataSource = channel.unary_unary(
                '/pomerium.dashboard.ExternalDataSourceService/GetExternalDataSource',
                request_serializer=external__data__sources__pb2.GetExternalDataSourceRequest.SerializeToString,
                response_deserializer=external__data__sources__pb2.GetExternalDataSourceResponse.FromString,
                )
        self.ListExternalDataSources = channel.unary_unary(
                '/pomerium.dashboard.ExternalDataSourceService/ListExternalDataSources',
                request_serializer=external__data__sources__pb2.ListExternalDataSourcesRequest.SerializeToString,
                response_deserializer=external__data__sources__pb2.ListExternalDataSourcesResponse.FromString,
                )
        self.ListExternalDataSourceRecordTypes = channel.unary_unary(
                '/pomerium.dashboard.ExternalDataSourceService/ListExternalDataSourceRecordTypes',
                request_serializer=external__data__sources__pb2.ListExternalDataSourceRecordTypesRequest.SerializeToString,
                response_deserializer=external__data__sources__pb2.ListExternalDataSourceRecordTypesResponse.FromString,
                )
        self.ListExternalDataSourceRecordFields = channel.unary_unary(
                '/pomerium.dashboard.ExternalDataSourceService/ListExternalDataSourceRecordFields',
                request_serializer=external__data__sources__pb2.ListExternalDataSourceRecordFieldsRequest.SerializeToString,
                response_deserializer=external__data__sources__pb2.ListExternalDataSourceRecordFieldsResponse.FromString,
                )
        self.SetExternalDataSource = channel.unary_unary(
                '/pomerium.dashboard.ExternalDataSourceService/SetExternalDataSource',
                request_serializer=external__data__sources__pb2.SetExternalDataSourceRequest.SerializeToString,
                response_deserializer=external__data__sources__pb2.SetExternalDataSourceResponse.FromString,
                )


class ExternalDataSourceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DeleteExternalDataSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExternalDataSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListExternalDataSources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListExternalDataSourceRecordTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListExternalDataSourceRecordFields(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetExternalDataSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExternalDataSourceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeleteExternalDataSource': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteExternalDataSource,
                    request_deserializer=external__data__sources__pb2.DeleteExternalDataSourceRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetExternalDataSource': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExternalDataSource,
                    request_deserializer=external__data__sources__pb2.GetExternalDataSourceRequest.FromString,
                    response_serializer=external__data__sources__pb2.GetExternalDataSourceResponse.SerializeToString,
            ),
            'ListExternalDataSources': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExternalDataSources,
                    request_deserializer=external__data__sources__pb2.ListExternalDataSourcesRequest.FromString,
                    response_serializer=external__data__sources__pb2.ListExternalDataSourcesResponse.SerializeToString,
            ),
            'ListExternalDataSourceRecordTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExternalDataSourceRecordTypes,
                    request_deserializer=external__data__sources__pb2.ListExternalDataSourceRecordTypesRequest.FromString,
                    response_serializer=external__data__sources__pb2.ListExternalDataSourceRecordTypesResponse.SerializeToString,
            ),
            'ListExternalDataSourceRecordFields': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExternalDataSourceRecordFields,
                    request_deserializer=external__data__sources__pb2.ListExternalDataSourceRecordFieldsRequest.FromString,
                    response_serializer=external__data__sources__pb2.ListExternalDataSourceRecordFieldsResponse.SerializeToString,
            ),
            'SetExternalDataSource': grpc.unary_unary_rpc_method_handler(
                    servicer.SetExternalDataSource,
                    request_deserializer=external__data__sources__pb2.SetExternalDataSourceRequest.FromString,
                    response_serializer=external__data__sources__pb2.SetExternalDataSourceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pomerium.dashboard.ExternalDataSourceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExternalDataSourceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeleteExternalDataSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pomerium.dashboard.ExternalDataSourceService/DeleteExternalDataSource',
            external__data__sources__pb2.DeleteExternalDataSourceRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetExternalDataSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pomerium.dashboard.ExternalDataSourceService/GetExternalDataSource',
            external__data__sources__pb2.GetExternalDataSourceRequest.SerializeToString,
            external__data__sources__pb2.GetExternalDataSourceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListExternalDataSources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pomerium.dashboard.ExternalDataSourceService/ListExternalDataSources',
            external__data__sources__pb2.ListExternalDataSourcesRequest.SerializeToString,
            external__data__sources__pb2.ListExternalDataSourcesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListExternalDataSourceRecordTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pomerium.dashboard.ExternalDataSourceService/ListExternalDataSourceRecordTypes',
            external__data__sources__pb2.ListExternalDataSourceRecordTypesRequest.SerializeToString,
            external__data__sources__pb2.ListExternalDataSourceRecordTypesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListExternalDataSourceRecordFields(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pomerium.dashboard.ExternalDataSourceService/ListExternalDataSourceRecordFields',
            external__data__sources__pb2.ListExternalDataSourceRecordFieldsRequest.SerializeToString,
            external__data__sources__pb2.ListExternalDataSourceRecordFieldsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetExternalDataSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pomerium.dashboard.ExternalDataSourceService/SetExternalDataSource',
            external__data__sources__pb2.SetExternalDataSourceRequest.SerializeToString,
            external__data__sources__pb2.SetExternalDataSourceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
