"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ExternalDataSource(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class HeadersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    ORIGINATOR_ID_FIELD_NUMBER: builtins.int
    CLUSTER_ID_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    MODIFIED_AT_FIELD_NUMBER: builtins.int
    DELETED_AT_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    RECORD_TYPE_FIELD_NUMBER: builtins.int
    FOREIGN_KEY_FIELD_NUMBER: builtins.int
    HEADERS_FIELD_NUMBER: builtins.int
    ALLOW_INSECURE_TLS_FIELD_NUMBER: builtins.int
    CLIENT_TLS_KEY_ID_FIELD_NUMBER: builtins.int
    POLLING_MIN_DELAY_FIELD_NUMBER: builtins.int
    POLLING_MAX_DELAY_FIELD_NUMBER: builtins.int
    id: builtins.str
    originator_id: builtins.str
    cluster_id: builtins.str
    url: builtins.str
    """Url is the URL to query for data."""
    record_type: builtins.str
    """RecordType is how the queried records will be stored in the databroker."""
    foreign_key: builtins.str
    """ForeignKey is the key referenced for policy evaluation. E.g. user.id."""
    allow_insecure_tls: builtins.bool
    """AllowInsecureTls ignores TLS errors from the external data source."""
    client_tls_key_id: builtins.str
    """ClientTlsKeyId is the key pair used for TLS to the external data source."""
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def modified_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def deleted_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def headers(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Headers are request headers sent to the external data source."""

    @property
    def polling_min_delay(self) -> google.protobuf.duration_pb2.Duration:
        """PollingMinDelay is the minimum amount of time to wait before polling again."""

    @property
    def polling_max_delay(self) -> google.protobuf.duration_pb2.Duration:
        """PollingMaxDelay is the maximum amount of time to wait before polling again."""

    def __init__(
        self,
        *,
        id: builtins.str = ...,
        originator_id: builtins.str = ...,
        cluster_id: builtins.str | None = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        modified_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        deleted_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        url: builtins.str = ...,
        record_type: builtins.str = ...,
        foreign_key: builtins.str = ...,
        headers: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        allow_insecure_tls: builtins.bool | None = ...,
        client_tls_key_id: builtins.str | None = ...,
        polling_min_delay: google.protobuf.duration_pb2.Duration | None = ...,
        polling_max_delay: google.protobuf.duration_pb2.Duration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_allow_insecure_tls", b"_allow_insecure_tls", "_client_tls_key_id", b"_client_tls_key_id", "_cluster_id", b"_cluster_id", "_polling_max_delay", b"_polling_max_delay", "_polling_min_delay", b"_polling_min_delay", "allow_insecure_tls", b"allow_insecure_tls", "client_tls_key_id", b"client_tls_key_id", "cluster_id", b"cluster_id", "created_at", b"created_at", "deleted_at", b"deleted_at", "modified_at", b"modified_at", "polling_max_delay", b"polling_max_delay", "polling_min_delay", b"polling_min_delay"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_allow_insecure_tls", b"_allow_insecure_tls", "_client_tls_key_id", b"_client_tls_key_id", "_cluster_id", b"_cluster_id", "_polling_max_delay", b"_polling_max_delay", "_polling_min_delay", b"_polling_min_delay", "allow_insecure_tls", b"allow_insecure_tls", "client_tls_key_id", b"client_tls_key_id", "cluster_id", b"cluster_id", "created_at", b"created_at", "deleted_at", b"deleted_at", "foreign_key", b"foreign_key", "headers", b"headers", "id", b"id", "modified_at", b"modified_at", "originator_id", b"originator_id", "polling_max_delay", b"polling_max_delay", "polling_min_delay", b"polling_min_delay", "record_type", b"record_type", "url", b"url"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_allow_insecure_tls", b"_allow_insecure_tls"]) -> typing.Literal["allow_insecure_tls"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_client_tls_key_id", b"_client_tls_key_id"]) -> typing.Literal["client_tls_key_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_cluster_id", b"_cluster_id"]) -> typing.Literal["cluster_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_polling_max_delay", b"_polling_max_delay"]) -> typing.Literal["polling_max_delay"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_polling_min_delay", b"_polling_min_delay"]) -> typing.Literal["polling_min_delay"] | None: ...

global___ExternalDataSource = ExternalDataSource

@typing.final
class DeleteExternalDataSourceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___DeleteExternalDataSourceRequest = DeleteExternalDataSourceRequest

@typing.final
class GetExternalDataSourceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___GetExternalDataSourceRequest = GetExternalDataSourceRequest

@typing.final
class GetExternalDataSourceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXTERNAL_DATA_SOURCE_FIELD_NUMBER: builtins.int
    @property
    def external_data_source(self) -> global___ExternalDataSource: ...
    def __init__(
        self,
        *,
        external_data_source: global___ExternalDataSource | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["external_data_source", b"external_data_source"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["external_data_source", b"external_data_source"]) -> None: ...

global___GetExternalDataSourceResponse = GetExternalDataSourceResponse

@typing.final
class ListExternalDataSourcesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLUSTER_ID_FIELD_NUMBER: builtins.int
    cluster_id: builtins.str
    def __init__(
        self,
        *,
        cluster_id: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_cluster_id", b"_cluster_id", "cluster_id", b"cluster_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_cluster_id", b"_cluster_id", "cluster_id", b"cluster_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_cluster_id", b"_cluster_id"]) -> typing.Literal["cluster_id"] | None: ...

global___ListExternalDataSourcesRequest = ListExternalDataSourcesRequest

@typing.final
class ListExternalDataSourcesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXTERNAL_DATA_SOURCES_FIELD_NUMBER: builtins.int
    @property
    def external_data_sources(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ExternalDataSource]: ...
    def __init__(
        self,
        *,
        external_data_sources: collections.abc.Iterable[global___ExternalDataSource] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["external_data_sources", b"external_data_sources"]) -> None: ...

global___ListExternalDataSourcesResponse = ListExternalDataSourcesResponse

@typing.final
class ListExternalDataSourceRecordTypesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLUSTER_ID_FIELD_NUMBER: builtins.int
    cluster_id: builtins.str
    def __init__(
        self,
        *,
        cluster_id: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_cluster_id", b"_cluster_id", "cluster_id", b"cluster_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_cluster_id", b"_cluster_id", "cluster_id", b"cluster_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_cluster_id", b"_cluster_id"]) -> typing.Literal["cluster_id"] | None: ...

global___ListExternalDataSourceRecordTypesRequest = ListExternalDataSourceRecordTypesRequest

@typing.final
class ListExternalDataSourceRecordTypesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORD_TYPES_FIELD_NUMBER: builtins.int
    @property
    def record_types(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        record_types: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["record_types", b"record_types"]) -> None: ...

global___ListExternalDataSourceRecordTypesResponse = ListExternalDataSourceRecordTypesResponse

@typing.final
class ListExternalDataSourceRecordFieldsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORD_TYPE_FIELD_NUMBER: builtins.int
    CLUSTER_ID_FIELD_NUMBER: builtins.int
    record_type: builtins.str
    cluster_id: builtins.str
    def __init__(
        self,
        *,
        record_type: builtins.str = ...,
        cluster_id: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_cluster_id", b"_cluster_id", "cluster_id", b"cluster_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_cluster_id", b"_cluster_id", "cluster_id", b"cluster_id", "record_type", b"record_type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_cluster_id", b"_cluster_id"]) -> typing.Literal["cluster_id"] | None: ...

global___ListExternalDataSourceRecordFieldsRequest = ListExternalDataSourceRecordFieldsRequest

@typing.final
class ListExternalDataSourceRecordFieldsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORD_FIELDS_FIELD_NUMBER: builtins.int
    @property
    def record_fields(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        record_fields: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["record_fields", b"record_fields"]) -> None: ...

global___ListExternalDataSourceRecordFieldsResponse = ListExternalDataSourceRecordFieldsResponse

@typing.final
class SetExternalDataSourceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXTERNAL_DATA_SOURCE_FIELD_NUMBER: builtins.int
    @property
    def external_data_source(self) -> global___ExternalDataSource: ...
    def __init__(
        self,
        *,
        external_data_source: global___ExternalDataSource | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["external_data_source", b"external_data_source"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["external_data_source", b"external_data_source"]) -> None: ...

global___SetExternalDataSourceRequest = SetExternalDataSourceRequest

@typing.final
class SetExternalDataSourceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXTERNAL_DATA_SOURCE_FIELD_NUMBER: builtins.int
    @property
    def external_data_source(self) -> global___ExternalDataSource: ...
    def __init__(
        self,
        *,
        external_data_source: global___ExternalDataSource | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["external_data_source", b"external_data_source"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["external_data_source", b"external_data_source"]) -> None: ...

global___SetExternalDataSourceResponse = SetExternalDataSourceResponse
