#!/bin/bash
set -euo pipefail

_scripts_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
_root_dir="$(dirname "$_scripts_dir")"
_deps_dir="$_root_dir/deps"

readonly _git_deps=(
    "pomerium/enterprise-client|d7a41a10d10c9a499e5cc9d9f93ab2c53dfe87b1"
    'envoyproxy/protoc-gen-validate|v1.0.2'
    'census-instrumentation/opencensus-proto|v0.4.1'
    'open-telemetry/opentelemetry-proto|v1.0.0'
)

function replace-in-file() {
    if [ "$(uname)" = 'Darwin' ]; then
        # for MacOS
        sed -i '' -E "$1" "$2"
    else
        # for Linux and Windows
        sed -i'' -E "$1" "$2"
    fi
}

function clone() {
    local _name="$1"
    local _tag="$2"
    local _dst="$3"

    echo "cloning $_name:$_tag to $_dst"
    if [ ! -d "$_dst" ]; then
        mkdir -p "$_dst"
        git clone "git@github.com:$_name" "$_dst"
    fi
    (
        cd "$_dst"
        git fetch
        git checkout "$_tag"
    )
}

function clone_all() {
    local _name _tag _dst
    for _dep in "${_git_deps[@]}"; do
        IFS=$'|' read -r _name _tag <<<"$_dep"
        _dst="$_deps_dir/github.com/$_name"
        clone "$_name" "$_tag" "$_dst"
    done
}

function download() {
    local _url="$1"
    local _dst="$2"

    echo "downloading $_url to $_dst"
    curl \
        --silent \
        --compressed \
        --fail \
        --location \
        --time-cond "$_dst" \
        --output "$_dst" \
        "$_url"
}

function join_by() {
    local IFS="$1"
    shift
    echo "$*"
}

clone_all

_proto_files=(
    activity_log.proto
    clusters.proto
    devices.proto
    external_data_sources.proto
    key_chain.proto
    namespaces.proto
    policy.proto
    report.proto
    route_health_check.proto
    route_redirect_action.proto
    routes.proto
    settings.proto
    types.proto
    users.proto
)

echo "installing python dependencies"
pip install \
    'wheel==0.45.1' \
    'protobuf==5.29.4' \
    'grpcio==1.71.0' \
    'grpcio-tools==1.71.0' \
    'mypy-protobuf==3.6.0'

(
    cd "$_root_dir"

    echo "generating dependency protobuf code"
    python -m grpc_tools.protoc \
        -I "$_deps_dir/github.com/envoyproxy/protoc-gen-validate" \
        -I "$_deps_dir/github.com/census-instrumentation/opencensus-proto/src" \
        -I "$_deps_dir/github.com/open-telemetry/opentelemetry-proto" \
        -I "$_deps_dir/github.com/prometheus/client_model" \
        --python_out="src" \
        $(cd deps/github.com/envoyproxy/protoc-gen-validate && find . -regex '.*\.proto' | sed 's|^./||')

    echo "generating enterprise-client protobuf code"
    mkdir -p src/pomerium/pb
    python -m grpc_tools.protoc \
        -I "$_deps_dir" \
        -I "$_deps_dir/github.com/envoyproxy/protoc-gen-validate" \
        -I "$_deps_dir/github.com/pomerium/enterprise-client/protos/pomerium-console" \
        --mypy_out="src/pomerium/pb" \
        --mypy_grpc_out="src/pomerium/pb" \
        --python_out="src/pomerium/pb" \
        --grpc_python_out="src/pomerium/pb" \
        "${_proto_files[@]}"

    # fix package names for grpc
    for _file in src/pomerium/pb/*.py; do
        replace-in-file 's/^import ([a-z_]+)_pb2/import pomerium.pb.\1_pb2/' "$_file"
    done

    # add __init__ files
    find src -type d -exec touch __init__.py \;
    rm __init__.py
)
