# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tests/harness/cases/bool.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tests/harness/cases/bool.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etests/harness/cases/bool.proto\x12\x13tests.harness.cases\x1a\x17validate/validate.proto\"\x17\n\x08\x42oolNone\x12\x0b\n\x03val\x18\x01 \x01(\x08\"%\n\rBoolConstTrue\x12\x14\n\x03val\x18\x01 \x01(\x08\x42\x07\xfa\x42\x04j\x02\x08\x01\"&\n\x0e\x42oolConstFalse\x12\x14\n\x03val\x18\x01 \x01(\x08\x42\x07\xfa\x42\x04j\x02\x08\x00\x42HZFgithub.com/envoyproxy/protoc-gen-validate/tests/harness/cases/go;casesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tests.harness.cases.bool_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZFgithub.com/envoyproxy/protoc-gen-validate/tests/harness/cases/go;cases'
  _globals['_BOOLCONSTTRUE'].fields_by_name['val']._loaded_options = None
  _globals['_BOOLCONSTTRUE'].fields_by_name['val']._serialized_options = b'\372B\004j\002\010\001'
  _globals['_BOOLCONSTFALSE'].fields_by_name['val']._loaded_options = None
  _globals['_BOOLCONSTFALSE'].fields_by_name['val']._serialized_options = b'\372B\004j\002\010\000'
  _globals['_BOOLNONE']._serialized_start=80
  _globals['_BOOLNONE']._serialized_end=103
  _globals['_BOOLCONSTTRUE']._serialized_start=105
  _globals['_BOOLCONSTTRUE']._serialized_end=142
  _globals['_BOOLCONSTFALSE']._serialized_start=144
  _globals['_BOOLCONSTFALSE']._serialized_end=182
# @@protoc_insertion_point(module_scope)
