# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/harness/cases/messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tests.harness.cases.other_package import embed_pb2 as tests_dot_harness_dot_cases_dot_other__package_dot_embed__pb2
from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"tests/harness/cases/messages.proto\x12\x13tests.harness.cases\x1a-tests/harness/cases/other_package/embed.proto\x1a\x17validate/validate.proto\"R\n\x07TestMsg\x12\x19\n\x05\x63onst\x18\x01 \x01(\tB\n\xfa\x42\x07r\x05\n\x03\x66oo\x12,\n\x06nested\x18\x02 \x01(\x0b\x32\x1c.tests.harness.cases.TestMsg\"O\n\x0bMessageNone\x12\x35\n\x03val\x18\x01 \x01(\x0b\x32(.tests.harness.cases.MessageNone.NoneMsg\x1a\t\n\x07NoneMsg\",\n\x0fMessageDisabled\x12\x14\n\x03val\x18\x01 \x01(\x04\x42\x07\xfa\x42\x04\x32\x02 {:\x03\xf8\x42\x01\"+\n\x0eMessageIgnored\x12\x14\n\x03val\x18\x01 \x01(\x04\x42\x07\xfa\x42\x04\x32\x02 {:\x03\x80\x43\x01\"4\n\x07Message\x12)\n\x03val\x18\x01 \x01(\x0b\x32\x1c.tests.harness.cases.TestMsg\"L\n\x13MessageCrossPackage\x12\x35\n\x03val\x18\x01 \x01(\x0b\x32(.tests.harness.cases.other_package.Embed\"B\n\x0bMessageSkip\x12\x33\n\x03val\x18\x01 \x01(\x0b\x32\x1c.tests.harness.cases.TestMsgB\x08\xfa\x42\x05\x8a\x01\x02\x08\x01\"F\n\x0fMessageRequired\x12\x33\n\x03val\x18\x01 \x01(\x0b\x32\x1c.tests.harness.cases.TestMsgB\x08\xfa\x42\x05\x8a\x01\x02\x10\x01\"Y\n\x14MessageRequiredOneof\x12\x35\n\x03val\x18\x01 \x01(\x0b\x32\x1c.tests.harness.cases.TestMsgB\x08\xfa\x42\x05\x8a\x01\x02\x10\x01H\x00\x42\n\n\x03one\x12\x03\xf8\x42\x01\"\x15\n\x13MessageWith3dInsideBHZFgithub.com/envoyproxy/protoc-gen-validate/tests/harness/cases/go;casesb\x06proto3')



_TESTMSG = DESCRIPTOR.message_types_by_name['TestMsg']
_MESSAGENONE = DESCRIPTOR.message_types_by_name['MessageNone']
_MESSAGENONE_NONEMSG = _MESSAGENONE.nested_types_by_name['NoneMsg']
_MESSAGEDISABLED = DESCRIPTOR.message_types_by_name['MessageDisabled']
_MESSAGEIGNORED = DESCRIPTOR.message_types_by_name['MessageIgnored']
_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_MESSAGECROSSPACKAGE = DESCRIPTOR.message_types_by_name['MessageCrossPackage']
_MESSAGESKIP = DESCRIPTOR.message_types_by_name['MessageSkip']
_MESSAGEREQUIRED = DESCRIPTOR.message_types_by_name['MessageRequired']
_MESSAGEREQUIREDONEOF = DESCRIPTOR.message_types_by_name['MessageRequiredOneof']
_MESSAGEWITH3DINSIDE = DESCRIPTOR.message_types_by_name['MessageWith3dInside']
TestMsg = _reflection.GeneratedProtocolMessageType('TestMsg', (_message.Message,), {
  'DESCRIPTOR' : _TESTMSG,
  '__module__' : 'tests.harness.cases.messages_pb2'
  # @@protoc_insertion_point(class_scope:tests.harness.cases.TestMsg)
  })
_sym_db.RegisterMessage(TestMsg)

MessageNone = _reflection.GeneratedProtocolMessageType('MessageNone', (_message.Message,), {

  'NoneMsg' : _reflection.GeneratedProtocolMessageType('NoneMsg', (_message.Message,), {
    'DESCRIPTOR' : _MESSAGENONE_NONEMSG,
    '__module__' : 'tests.harness.cases.messages_pb2'
    # @@protoc_insertion_point(class_scope:tests.harness.cases.MessageNone.NoneMsg)
    })
  ,
  'DESCRIPTOR' : _MESSAGENONE,
  '__module__' : 'tests.harness.cases.messages_pb2'
  # @@protoc_insertion_point(class_scope:tests.harness.cases.MessageNone)
  })
_sym_db.RegisterMessage(MessageNone)
_sym_db.RegisterMessage(MessageNone.NoneMsg)

MessageDisabled = _reflection.GeneratedProtocolMessageType('MessageDisabled', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEDISABLED,
  '__module__' : 'tests.harness.cases.messages_pb2'
  # @@protoc_insertion_point(class_scope:tests.harness.cases.MessageDisabled)
  })
_sym_db.RegisterMessage(MessageDisabled)

MessageIgnored = _reflection.GeneratedProtocolMessageType('MessageIgnored', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEIGNORED,
  '__module__' : 'tests.harness.cases.messages_pb2'
  # @@protoc_insertion_point(class_scope:tests.harness.cases.MessageIgnored)
  })
_sym_db.RegisterMessage(MessageIgnored)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'tests.harness.cases.messages_pb2'
  # @@protoc_insertion_point(class_scope:tests.harness.cases.Message)
  })
_sym_db.RegisterMessage(Message)

MessageCrossPackage = _reflection.GeneratedProtocolMessageType('MessageCrossPackage', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGECROSSPACKAGE,
  '__module__' : 'tests.harness.cases.messages_pb2'
  # @@protoc_insertion_point(class_scope:tests.harness.cases.MessageCrossPackage)
  })
_sym_db.RegisterMessage(MessageCrossPackage)

MessageSkip = _reflection.GeneratedProtocolMessageType('MessageSkip', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGESKIP,
  '__module__' : 'tests.harness.cases.messages_pb2'
  # @@protoc_insertion_point(class_scope:tests.harness.cases.MessageSkip)
  })
_sym_db.RegisterMessage(MessageSkip)

MessageRequired = _reflection.GeneratedProtocolMessageType('MessageRequired', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEREQUIRED,
  '__module__' : 'tests.harness.cases.messages_pb2'
  # @@protoc_insertion_point(class_scope:tests.harness.cases.MessageRequired)
  })
_sym_db.RegisterMessage(MessageRequired)

MessageRequiredOneof = _reflection.GeneratedProtocolMessageType('MessageRequiredOneof', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEREQUIREDONEOF,
  '__module__' : 'tests.harness.cases.messages_pb2'
  # @@protoc_insertion_point(class_scope:tests.harness.cases.MessageRequiredOneof)
  })
_sym_db.RegisterMessage(MessageRequiredOneof)

MessageWith3dInside = _reflection.GeneratedProtocolMessageType('MessageWith3dInside', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEWITH3DINSIDE,
  '__module__' : 'tests.harness.cases.messages_pb2'
  # @@protoc_insertion_point(class_scope:tests.harness.cases.MessageWith3dInside)
  })
_sym_db.RegisterMessage(MessageWith3dInside)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZFgithub.com/envoyproxy/protoc-gen-validate/tests/harness/cases/go;cases'
  _TESTMSG.fields_by_name['const']._options = None
  _TESTMSG.fields_by_name['const']._serialized_options = b'\372B\007r\005\n\003foo'
  _MESSAGEDISABLED.fields_by_name['val']._options = None
  _MESSAGEDISABLED.fields_by_name['val']._serialized_options = b'\372B\0042\002 {'
  _MESSAGEDISABLED._options = None
  _MESSAGEDISABLED._serialized_options = b'\370B\001'
  _MESSAGEIGNORED.fields_by_name['val']._options = None
  _MESSAGEIGNORED.fields_by_name['val']._serialized_options = b'\372B\0042\002 {'
  _MESSAGEIGNORED._options = None
  _MESSAGEIGNORED._serialized_options = b'\200C\001'
  _MESSAGESKIP.fields_by_name['val']._options = None
  _MESSAGESKIP.fields_by_name['val']._serialized_options = b'\372B\005\212\001\002\010\001'
  _MESSAGEREQUIRED.fields_by_name['val']._options = None
  _MESSAGEREQUIRED.fields_by_name['val']._serialized_options = b'\372B\005\212\001\002\020\001'
  _MESSAGEREQUIREDONEOF.oneofs_by_name['one']._options = None
  _MESSAGEREQUIREDONEOF.oneofs_by_name['one']._serialized_options = b'\370B\001'
  _MESSAGEREQUIREDONEOF.fields_by_name['val']._options = None
  _MESSAGEREQUIREDONEOF.fields_by_name['val']._serialized_options = b'\372B\005\212\001\002\020\001'
  _TESTMSG._serialized_start=131
  _TESTMSG._serialized_end=213
  _MESSAGENONE._serialized_start=215
  _MESSAGENONE._serialized_end=294
  _MESSAGENONE_NONEMSG._serialized_start=285
  _MESSAGENONE_NONEMSG._serialized_end=294
  _MESSAGEDISABLED._serialized_start=296
  _MESSAGEDISABLED._serialized_end=340
  _MESSAGEIGNORED._serialized_start=342
  _MESSAGEIGNORED._serialized_end=385
  _MESSAGE._serialized_start=387
  _MESSAGE._serialized_end=439
  _MESSAGECROSSPACKAGE._serialized_start=441
  _MESSAGECROSSPACKAGE._serialized_end=517
  _MESSAGESKIP._serialized_start=519
  _MESSAGESKIP._serialized_end=585
  _MESSAGEREQUIRED._serialized_start=587
  _MESSAGEREQUIRED._serialized_end=657
  _MESSAGEREQUIREDONEOF._serialized_start=659
  _MESSAGEREQUIREDONEOF._serialized_end=748
  _MESSAGEWITH3DINSIDE._serialized_start=750
  _MESSAGEWITH3DINSIDE._serialized_end=771
# @@protoc_insertion_point(module_scope)
