# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/harness/cases/oneofs.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n tests/harness/cases/oneofs.proto\x12\x13tests.harness.cases\x1a\x17validate/validate.proto\"$\n\x0cTestOneOfMsg\x12\x14\n\x03val\x18\x01 \x01(\x08\x42\x07\xfa\x42\x04j\x02\x08\x01\"*\n\tOneOfNone\x12\x0b\n\x01x\x18\x01 \x01(\tH\x00\x12\x0b\n\x01y\x18\x02 \x01(\x05H\x00\x42\x03\n\x01o\"k\n\x05OneOf\x12\x17\n\x01x\x18\x01 \x01(\tB\n\xfa\x42\x07r\x05:\x03\x66ooH\x00\x12\x14\n\x01y\x18\x02 \x01(\x05\x42\x07\xfa\x42\x04\x1a\x02 \x00H\x00\x12.\n\x01z\x18\x03 \x01(\x0b\x32!.tests.harness.cases.TestOneOfMsgH\x00\x42\x03\n\x01o\"r\n\rOneOfRequired\x12\x0b\n\x01x\x18\x01 \x01(\tH\x00\x12\x0b\n\x01y\x18\x02 \x01(\x05H\x00\x12\x1f\n\x15name_with_underscores\x18\x03 \x01(\x05H\x00\x12\x1c\n\x12under_and_1_number\x18\x04 \x01(\x05H\x00\x42\x08\n\x01o\x12\x03\xf8\x42\x01\"h\n\x10OneOfIgnoreEmpty\x12\x19\n\x01x\x18\x01 \x01(\tB\x0c\xfa\x42\tr\x07\x10\x03\x18\x05\xd0\x01\x01H\x00\x12\x18\n\x01y\x18\x02 \x01(\x0c\x42\x0b\xfa\x42\x08z\x06\x10\x03\x18\x05p\x01H\x00\x12\x1a\n\x01z\x18\x03 \x01(\x05\x42\r\xfa\x42\n\x1a\x08\x18\x80\x01(\x80\x02@\x01H\x00\x42\x03\n\x01oBHZFgithub.com/envoyproxy/protoc-gen-validate/tests/harness/cases/go;casesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tests.harness.cases.oneofs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZFgithub.com/envoyproxy/protoc-gen-validate/tests/harness/cases/go;cases'
  _globals['_TESTONEOFMSG'].fields_by_name['val']._options = None
  _globals['_TESTONEOFMSG'].fields_by_name['val']._serialized_options = b'\372B\004j\002\010\001'
  _globals['_ONEOF'].fields_by_name['x']._options = None
  _globals['_ONEOF'].fields_by_name['x']._serialized_options = b'\372B\007r\005:\003foo'
  _globals['_ONEOF'].fields_by_name['y']._options = None
  _globals['_ONEOF'].fields_by_name['y']._serialized_options = b'\372B\004\032\002 \000'
  _globals['_ONEOFREQUIRED'].oneofs_by_name['o']._options = None
  _globals['_ONEOFREQUIRED'].oneofs_by_name['o']._serialized_options = b'\370B\001'
  _globals['_ONEOFIGNOREEMPTY'].fields_by_name['x']._options = None
  _globals['_ONEOFIGNOREEMPTY'].fields_by_name['x']._serialized_options = b'\372B\tr\007\020\003\030\005\320\001\001'
  _globals['_ONEOFIGNOREEMPTY'].fields_by_name['y']._options = None
  _globals['_ONEOFIGNOREEMPTY'].fields_by_name['y']._serialized_options = b'\372B\010z\006\020\003\030\005p\001'
  _globals['_ONEOFIGNOREEMPTY'].fields_by_name['z']._options = None
  _globals['_ONEOFIGNOREEMPTY'].fields_by_name['z']._serialized_options = b'\372B\n\032\010\030\200\001(\200\002@\001'
  _globals['_TESTONEOFMSG']._serialized_start=82
  _globals['_TESTONEOFMSG']._serialized_end=118
  _globals['_ONEOFNONE']._serialized_start=120
  _globals['_ONEOFNONE']._serialized_end=162
  _globals['_ONEOF']._serialized_start=164
  _globals['_ONEOF']._serialized_end=271
  _globals['_ONEOFREQUIRED']._serialized_start=273
  _globals['_ONEOFREQUIRED']._serialized_end=387
  _globals['_ONEOFIGNOREEMPTY']._serialized_start=389
  _globals['_ONEOFIGNOREEMPTY']._serialized_end=493
# @@protoc_insertion_point(module_scope)
