"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class RateLimitUnit(_RateLimitUnit, metaclass=_RateLimitUnitEnumTypeWrapper):
    """[#protodoc-title: Ratelimit Time Unit]

    Identifies the unit of of time for rate limit.
    """
    pass
class _RateLimitUnit:
    V = typing.NewType('V', builtins.int)
class _RateLimitUnitEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RateLimitUnit.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    UNKNOWN = RateLimitUnit.V(0)
    """The time unit is not known."""

    SECOND = RateLimitUnit.V(1)
    """The time unit representing a second."""

    MINUTE = RateLimitUnit.V(2)
    """The time unit representing a minute."""

    HOUR = RateLimitUnit.V(3)
    """The time unit representing an hour."""

    DAY = RateLimitUnit.V(4)
    """The time unit representing a day."""


UNKNOWN = RateLimitUnit.V(0)
"""The time unit is not known."""

SECOND = RateLimitUnit.V(1)
"""The time unit representing a second."""

MINUTE = RateLimitUnit.V(2)
"""The time unit representing a minute."""

HOUR = RateLimitUnit.V(3)
"""The time unit representing an hour."""

DAY = RateLimitUnit.V(4)
"""The time unit representing a day."""

global___RateLimitUnit = RateLimitUnit

