"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.descriptor_pb2
import google.protobuf.internal.extension_dict
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class MigrateAnnotation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RENAME_FIELD_NUMBER: builtins.int
    rename: typing.Text = ...
    """Rename the message/enum/enum value in next version."""

    def __init__(self,
        *,
        rename : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"rename",b"rename"]) -> None: ...
global___MigrateAnnotation = MigrateAnnotation

class FieldMigrateAnnotation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RENAME_FIELD_NUMBER: builtins.int
    ONEOF_PROMOTION_FIELD_NUMBER: builtins.int
    rename: typing.Text = ...
    """Rename the field in next version."""

    oneof_promotion: typing.Text = ...
    """Add the field to a named oneof in next version. If this already exists, the
    field will join its siblings under the oneof, otherwise a new oneof will be
    created with the given name.
    """

    def __init__(self,
        *,
        rename : typing.Text = ...,
        oneof_promotion : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"oneof_promotion",b"oneof_promotion",u"rename",b"rename"]) -> None: ...
global___FieldMigrateAnnotation = FieldMigrateAnnotation

class FileMigrateAnnotation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MOVE_TO_PACKAGE_FIELD_NUMBER: builtins.int
    move_to_package: typing.Text = ...
    """Move all types in the file to another package, this implies changing proto
    file path.
    """

    def __init__(self,
        *,
        move_to_package : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"move_to_package",b"move_to_package"]) -> None: ...
global___FileMigrateAnnotation = FileMigrateAnnotation

message_migrate: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.MessageOptions, global___MigrateAnnotation] = ...

field_migrate: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.FieldOptions, global___FieldMigrateAnnotation] = ...

enum_migrate: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.EnumOptions, global___MigrateAnnotation] = ...

enum_value_migrate: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.EnumValueOptions, global___MigrateAnnotation] = ...

file_migrate: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.FileOptions, global___FileMigrateAnnotation] = ...
