# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: java/pgv-java-stub/src/test/proto/underscoreName.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'java/pgv-java-stub/src/test/proto/underscoreName.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6java/pgv-java-stub/src/test/proto/underscoreName.proto\x12\x16io.envoyproxy.pgv.grpc\x1a\x17validate/validate.proto\"0\n\x1aMessageNameWith_Underscore\x12\x12\n\x01v\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x02\"7\n!AnotherMessageNameWith_Underscore\x12\x12\n\x01v\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x02\"4\n\x1eMessageNameWith_Two_Underscore\x12\x12\n\x01v\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x02\x42\x1e\n\x1aio.envoyproxy.pgv.validateP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'java.pgv_java_stub.src.test.proto.underscoreName_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032io.envoyproxy.pgv.validateP\001'
  _globals['_MESSAGENAMEWITH_UNDERSCORE'].fields_by_name['v']._loaded_options = None
  _globals['_MESSAGENAMEWITH_UNDERSCORE'].fields_by_name['v']._serialized_options = b'\372B\004r\002\020\002'
  _globals['_ANOTHERMESSAGENAMEWITH_UNDERSCORE'].fields_by_name['v']._loaded_options = None
  _globals['_ANOTHERMESSAGENAMEWITH_UNDERSCORE'].fields_by_name['v']._serialized_options = b'\372B\004r\002\020\002'
  _globals['_MESSAGENAMEWITH_TWO_UNDERSCORE'].fields_by_name['v']._loaded_options = None
  _globals['_MESSAGENAMEWITH_TWO_UNDERSCORE'].fields_by_name['v']._serialized_options = b'\372B\004r\002\020\002'
  _globals['_MESSAGENAMEWITH_UNDERSCORE']._serialized_start=107
  _globals['_MESSAGENAMEWITH_UNDERSCORE']._serialized_end=155
  _globals['_ANOTHERMESSAGENAMEWITH_UNDERSCORE']._serialized_start=157
  _globals['_ANOTHERMESSAGENAMEWITH_UNDERSCORE']._serialized_end=212
  _globals['_MESSAGENAMEWITH_TWO_UNDERSCORE']._serialized_start=214
  _globals['_MESSAGENAMEWITH_TWO_UNDERSCORE']._serialized_end=266
# @@protoc_insertion_point(module_scope)
