name: test

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install .

      - run: make test
